using System.Drawing;
using System.Linq;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Promotion {
    public class TpCmdlRelator {
        public static string FetchQuery = "SELECT * FROM TP_CMD";
    }

    [TableName ("TP_CMD")]
    public class TPCMDRecord : IAutoGeneratedRecord {
        [PrimaryKey ("Id")]
        public int Id {
            get;
            set;
        }

        public int name {
            get;
            set;
        }

        public int mapid {
            get;
            set;
        }

        public int cellid {
            get;
            set;
        }

        public int sens {
            get;
            set;
        }

    }
}