using System;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Accounts
{
    public class DB_Dioses_sacro_Relator
    {
        public static string FetchQuery = "SELECT * FROM characters_dioses_sacro";
        /// <summary>
        /// Use string.Format
        /// </summary>
        public static string FetchById = "SELECT * FROM characters_dioses_sacro WHERE CharacterId={0}";
    }

    [TableName("characters_dioses_sacro")]
    public class DB_Dioses_sacro : IAutoGeneratedRecord
    {
        public DB_Dioses_sacro()
        {
        }

        [Index]
        [PrimaryKey("CharacterId", false)]
        public int CharacterId
        {
            get;
            set;
        }

        public DateTime Tiempo_Dios
        {
            get;
            set;
        }

       



    }
}